In [47]:
import numpy as np
np.random.seed(seed=11)

In [48]:
arr = np.array(6)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print()

arrOne = np.array([6, 2])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print()

arrTwo = np.array([[6, 2], [5, 1]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

arrThree = np.array([[6, 2], [5, 1], [4, 0]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

6
0
()
1
int32

6
0
()
1
int32

6
0
()
1
int32
6
0
()
1
int32


In [49]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.random.random((2,3)))
print(np.eye(4)) # n x n

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.18026969 0.01947524 0.46321853]
 [0.72493393 0.4202036  0.4854271 ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
print(arrTwo[0])
print(arrThree[:, 1]) #col 1
print(arrThree[0, :]) # row 0


[6 2]
[2 1 0]
[6 2]


In [52]:
print(np.sum(arrTwo))
print(arrTwo.dot(arrTwo))
print(np.expand_dims(arrTwo, axis=1))

14
[[46 14]
 [35 11]]
[[[6 2]]

 [[5 1]]]
