In [1]:
import torch
import numpy as np
np.random.seed(seed=11)
torch.manual_seed(11)

In [2]:
print (torch.cuda.is_available())

True


In [3]:
# Tensors
tTorch = torch.randn(2, 3)
print(tTorch.type())
print(tTorch.shape)
print(tTorch.type)
print(tTorch)
print()

tTorch = torch.zeros(2, 3)
tTorch = torch.ones(2, 3)

lToTTorch = torch.Tensor([[1, 2, 3], [4, 5, 6]])

npToTorch = torch.Tensor(np.random.rand(2, 3))

chngTypeTensor = torch.Tensor(2, 3)
print(chngTypeTensor.type())
chngTypeTensor = chngTypeTensor.long()
print(chngTypeTensor.type())

torch.FloatTensor
torch.Size([2, 3])
<built-in method type of Tensor object at 0x000001B61C58DC70>
tensor([[ 0.7376,  1.9459, -0.6995],
        [-1.3023, -0.5133, -0.2696]])

torch.FloatTensor
torch.LongTensor


In [5]:
# Tensor operations

# Addition
a = torch.randn(2, 3)
b = torch.randn(2, 3)
c = a + b
print(a)
print(b)
print(c)
print()

# Dot product
d = torch.randn (3, 2)
print(d)
print(torch.mm(a, d))
print()

# Transpose
print(torch.t(a))
print()

# Reshape
print(a.view(6))
print()

# Sum per col then row
print(torch.sum(a, dim=0))
print(torch.sum(a, dim=1))
print()

# First row
print(a[:1])
print()

# Concat
print(torch.cat([a, b], dim=0))

# BMM, squeeze/unsqueeze

tensor([[-0.9691, -2.1354, -1.0431],
        [-1.7073,  1.3896,  0.1728]])
tensor([[-0.9835, -1.0937,  0.1318],
        [ 0.1943, -0.3390,  1.6594]])
tensor([[-1.9526, -3.2291, -0.9113],
        [-1.5131,  1.0506,  1.8322]])

tensor([[-0.2411, -0.8700],
        [-0.0385,  0.4584],
        [-1.4693,  0.6935]])
tensor([[ 1.8486, -0.8592],
        [ 0.1042,  2.2423]])

tensor([[-0.9691, -1.7073],
        [-2.1354,  1.3896],
        [-1.0431,  0.1728]])

tensor([-0.9691, -2.1354, -1.0431, -1.7073,  1.3896,  0.1728])

tensor([-2.6765, -0.7459, -0.8703])
tensor([-4.1476, -0.1450])

tensor([[-0.9691, -2.1354, -1.0431]])

tensor([[-0.9691, -2.1354, -1.0431],
        [-1.7073,  1.3896,  0.1728],
        [-0.9835, -1.0937,  0.1318],
        [ 0.1943, -0.3390,  1.6594]])


In [6]:
# Neural net
import torch.nn as nn

# At basic, forward no backward func needed
class Network(nn.module):
    def __init__(self):
        super(Network, self).__init__()
        # Set layers, basic cnn ex 6 output for 5x5
        self.conv1 = nn.conv2D(1, 6, 5)
        self.conv2 = nn.conv2D(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
        
    def num_flat_features(self, x):
        size = x.size()[1:] 
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
        

SyntaxError: incomplete input (2709595319.py, line 10)

In [ ]:
# Loading data through torchvision

import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))])

trainset = torchvision.datasets.CIFAR10(root='../data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4, shuffle=False, num_workers=2)